import {MOVES,validateCombo,loadCombos} from './combos.js';
import {inputLabel,captureInput} from './input.js';
export function mountComboEditor(onSave){const $=id=>document.getElementById(id);let storage;try{storage=localStorage;}catch{}let saved=loadCombos(storage),slot=0,draft=structuredClone(saved[0]);const panel=$('combo-editor'),rows=$('combo-steps');
let stopCapture=null;const trig=document.createElement('div');trig.className='combo-input-row';const trigLabel=document.createElement('span');const bindBtn=document.createElement('button');bindBtn.type='button';bindBtn.textContent='重绑触发键';
function showInput(){trigLabel.textContent='触发键：'+inputLabel(draft.input);$('combo-slot').options[slot].textContent='栏位 '+(slot+1)+' · '+inputLabel(draft.input);}
bindBtn.onclick=()=>{if(stopCapture){stopCapture();stopCapture=null;bindBtn.textContent='重绑触发键';message('已取消，触发键不变');return;}bindBtn.textContent='请按下按键 / 点击鼠标 / 按手柄…';stopCapture=captureInput(id=>{stopCapture=null;bindBtn.textContent='重绑触发键';draft.input=id;showInput();save();});};
trig.append(trigLabel,bindBtn);$('combo-slot').closest('label').after(trig);
function message(text){$('combo-message').textContent=text;}
function render(){rows.replaceChildren();$('combo-name').value=draft.name;$('combo-count').textContent=draft.steps.length+' / 12';showInput();draft.steps.forEach((step,i)=>{const row=document.createElement('li');const title=document.createElement('span');title.textContent=(i+1)+'. '+MOVES[step.move].label;row.append(title);if(MOVES[step.move].guard){const input=document.createElement('input');input.type='number';input.min='.2';input.max='3';input.step='.1';input.value=step.hold;input.setAttribute('aria-label','第 '+(i+1)+' 步防守秒数');input.onchange=()=>{const value=Number(input.value);step.hold=Number.isFinite(value)?Math.max(.2,Math.min(3,value)):.6;input.value=step.hold;save();};row.append(input);}for(const[label,delta]of[['上移',-1],['下移',1],['删除',0]]){const btn=document.createElement('button');btn.type='button';btn.textContent=label;btn.setAttribute('aria-label','第 '+(i+1)+' 步'+label);btn.disabled=delta!==0&&(i+delta<0||i+delta>=draft.steps.length);btn.onclick=()=>{if(!delta)draft.steps.splice(i,1);else[draft.steps[i],draft.steps[i+delta]]=[draft.steps[i+delta],draft.steps[i]];render();save();};row.append(btn);}rows.append(row);});}
$('combo-toggle').onclick=()=>{panel.hidden=!panel.hidden;$('combo-toggle').setAttribute('aria-expanded',String(!panel.hidden));};$('combo-close').onclick=()=>{panel.hidden=true;$('combo-toggle').setAttribute('aria-expanded','false');};
$('combo-slot').onchange=e=>{slot=Number(e.target.value);draft=structuredClone(saved[slot]);render();message('战斗中按 '+inputLabel(draft.input)+' 施放');};$('combo-name').oninput=e=>{draft.name=e.target.value;save();};
for(const[id,move]of Object.entries(MOVES)){const b=document.createElement('button');b.type='button';b.textContent='+ '+move.label;b.onclick=()=>{if(draft.steps.length>=12){message('每套最多 12 个动作');return;}draft.steps.push({move:id,hold:.6});render();save();};$('combo-library').append(b);}
function save(){try{const checked=validateCombo(draft);saved[slot]=checked;onSave(saved);saved.forEach((c,i)=>{$('combo-slot').options[i].textContent='栏位 '+(i+1)+' · '+inputLabel(c.input);});try{storage.setItem('da-ji-tou-jiao.combos.v1',JSON.stringify(saved));message(checked.steps.length?'已自动保存 · 战斗中按 '+inputLabel(checked.input)+' 施放':'已自动保存为空招式');}catch{message('本次游戏已生效；浏览器不允许持久保存');}}catch(e){message(e.message);}}render();return saved;}
