import {guardBlocks} from './guard.js';
import {enemyPose} from './rig.js';
import {initBody,isGone,mobility,damagePart,tickInjury,bleedRate} from './injury.js';
export const ATTACKS={punch:{duration:.42,active:.14,range:1.95,damage:38,push:3.4,cone:.74,r:.065},palm:{duration:.34,active:.11,range:1.85,damage:34,push:2.7,cone:.72,r:.085},kick:{duration:.65,active:.25,range:2.65,damage:48,push:8,cone:.62,r:.12}};
export function createState(){return {hp:100,time:0,wave:0,kills:0,enemies:[],attack:null,sides:{palm:0,kick:0,punch:0},waveDelay:1.5,inv:0,ended:false,nextId:0};}
export function beginAttack(s,type){if(s.ended||s.guard||!ATTACKS[type])return false;if(s.attack){const previous=s.attack;if(type!=='palm'||previous.type!=='palm'||previous.t<ATTACKS.palm.duration*.55||!previous.hit)return false;}s.attack={type,side:s.sides[type],t:0,hit:false};s.sides[type]^=1;return true;}
export function targetInReach(p,e,a){const dx=e.x-p.x,dz=e.z-p.z,d=Math.hypot(dx,dz);return d<=a.range+.4&&(-Math.sin(p.yaw)*dx-Math.cos(p.yaw)*dz)/Math.max(d,.001)>a.cone;}
export function enemyParts(e,p){const q=e.pose||enemyPose(e,0,0),yaw=Math.atan2(-(p.x-e.x),-(p.z-e.z)),c=Math.cos(yaw),s=Math.sin(yaw),W=v=>({x:e.x+v[0]*c+v[2]*s,y:v[1],z:e.z-v[0]*s+v[2]*c}),out=[];
 const add=(part,v,r)=>out.push({part,...W(v),r});const segment=(part,a,b,r)=>{const av=q[a],bv=q[b],steps=Math.ceil(Math.hypot(...av.map((v,i)=>v-bv[i]))/.065);for(let i=0;i<=steps;i++){const t=steps?i/steps:0;add(part,av.map((v,j)=>v+(bv[j]-v)*t),r);}};
 add('head',q.head,.22);segment('torso','hip','chest',.245);segment('torso','chest','neck',.20);
 for(const side of['L','R']){if(!isGone(e,side+'arm')){segment(side+'arm',side+'shoulder',side+'elbow',.085);segment(side+'arm',side+'elbow',side+'wrist',.085);add(side+'arm',q[side+'wrist'],.11);}if(!isGone(e,side+'leg')){segment(side+'leg',side+'hip',side+'knee',.09);segment(side+'leg',side+'knee',side+'ankle',.075);if(!isGone(e,side+'foot'))add(side+'foot',[q[side+'ankle'][0],q[side+'ankle'][1],q[side+'ankle'][2]-.09],.135);}}
 return out;}
// Swept attack volume: earliest physical contact wins, so forearms occlude the head.
export function strikeHit(p,e,c){const pitch=p.pitch||0,dir=[-Math.sin(p.yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(p.yaw)*Math.cos(pitch)],origin=[p.x,1.63,p.z];let best=null;for(const sp of enemyParts(e,p)){const v=[sp.x-origin[0],sp.y-origin[1],sp.z-origin[2]],along=v.reduce((n,x,i)=>n+x*dir[i],0),radius=sp.r+c.r,disc=radius*radius-(v.reduce((n,x)=>n+x*x,0)-along*along);if(disc<0)continue;const near=Math.max(0,along-Math.sqrt(disc));if(along+Math.sqrt(disc)<0||near>c.range)continue;if(!best||near<best.distance)best={part:sp.part,pos:[sp.x,sp.y,sp.z],distance:near,head:sp.part==='head'};}return best;}
function down(s,e,events,cause,attack){if(e.counted)return;e.counted=true;s.kills++;e.hp=0;e.wind=0;events.push({type:'down',enemy:e,head:cause==='head',cause,attack});}
export function tick(s,p,dt,arena=null,rng=Math.random){const events=[];if(s.ended)return events;s.time=(s.time||0)+dt;s.inv=Math.max(0,s.inv-dt);
 for(const e of s.enemies){if(e.hp<=0)continue;initBody(e);const cause=tickInjury(e,dt);if(cause){down(s,e,events,cause);continue;}if(e.reaction){e.reaction.age+=dt;if(e.reaction.age>=e.reaction.duration)e.reaction=null;}if(bleedRate(e)>0){e.drip=(e.drip||0)+dt;if(e.drip>.45){e.drip=0;events.push({type:'bleed',enemy:e});}}}
 if(s.enemies.every(e=>e.hp<=0)){s.waveDelay-=dt;if(s.waveDelay<=0){s.wave++;s.waveDelay=4;const count=Math.min(2+s.wave,9);for(let i=0;i<count;i++){const a=i/count*Math.PI*2+s.wave*.75;s.enemies.push(initBody({id:s.nextId++,x:Math.sin(a)*6.8,z:Math.cos(a)*6.8,hp:100,vx:0,vz:0,cool:.9+i*.45,wind:0,stun:0,phase:i,flash:0}));}if(arena)for(const e of s.enemies)arena.resolve(e,.4);events.push({type:'wave'});}}
 if(s.attack){const a=s.attack,c=ATTACKS[a.type];a.t+=dt;if(!a.hit&&a.t>=c.active){a.hit=true;const contacts=s.enemies.filter(e=>e.hp>0&&targetInReach(p,e,c)&&(!arena||arena.clear(p,e))).map(e=>({e,h:strikeHit(p,e,c)})).filter(x=>x.h).sort((a,b)=>a.h.distance-b.h.distance);const contact=contacts[0];if(contact){const{e,h}=contact,result=damagePart(e,h.part,c.damage,rng);const d=Math.hypot(e.x-p.x,e.z-p.z)||1;e.vx=(e.x-p.x)/d*c.push;e.vz=(e.z-p.z)/d*c.push;e.stun=a.type==='kick'?.70:.4;e.wind=0;e.flash=.13;e.reaction={age:0,duration:a.type==='kick'?.95:.6,type:a.type,head:h.head,side:a.side?1:-1};events.push({type:'hit',enemy:e,attack:a.type,head:h.head,part:h.part,pos:h.pos,damage:result.damage,blocked:h.part.endsWith('arm')});if(result.severed)events.push({type:'sever',enemy:e,part:h.part,pos:h.pos});if(result.stunned)events.push({type:'stunned',enemy:e});if(result.cause)down(s,e,events,result.cause,a.type);}else events.push({type:'miss'});}if(a.t>=c.duration)s.attack=null;}
 for(const e of s.enemies){if(e.hp<=0)continue;e.flash=Math.max(0,e.flash-dt);e.x+=e.vx*dt;e.z+=e.vz*dt;e.vx*=Math.exp(-5*dt);e.vz*=Math.exp(-5*dt);e.stun=Math.max(0,e.stun-dt);e.cool-=dt;const dx=p.x-e.x,dz=p.z-e.z,d=Math.hypot(dx,dz)||1,profile=mobility(e),arms=Number(!isGone(e,'Larm'))+Number(!isGone(e,'Rarm')),canAttack=arms>0&&profile.mode!=='stunned';e.guard=canAttack&&d<3&&e.wind<=0&&e.stun<=0&&profile.mode!=='crawl'&&profile.mode!=='drag'?(e.id%2?'torso':'head'):null;
 if(e.ko>0){e.wind=0;}else if(e.stun===0){if(e.wind>0){e.wind-=dt;if(e.wind<=0){if(canAttack&&d<(profile.mode==='crawl'||profile.mode==='drag'?1.1:1.65)&&s.inv===0&&(!arena||arena.clear(e,p))){const zone=e.attackZone||'torso',blocked=guardBlocks(s.guard,zone,p,e);if(!blocked)s.hp=Math.max(0,s.hp-(profile.mode==='crawl'||profile.mode==='drag'?6:12));s.inv=.6;events.push({type:blocked?'block':'hurt',zone});}e.cool=arms===1?2.1:1.45;}}else if(d<1.5&&e.cool<=0&&canAttack){e.wind=.65;e.attackCount=(e.attackCount||0)+1;e.attackZone=profile.mode==='crawl'||profile.mode==='drag'?'torso':(e.attackCount+e.id)%2?'head':'torso';e.attackSide=isGone(e,'Larm')?1:isGone(e,'Rarm')?0:e.id%2;}else if(d>1.05){const speed=(1.15+Math.min(s.wave,8)*.15)*profile.speed,target=arena?arena.steer(e,p):p,tx=target.x-e.x,tz=target.z-e.z,td=Math.hypot(tx,tz)||1;e.x+=tx/td*speed*dt;e.z+=tz/td*speed*dt;}}
 e.x=Math.max(-(arena?.bounds?.x||7.5),Math.min(arena?.bounds?.x||7.5,e.x));e.z=Math.max(-(arena?.bounds?.z||7.5),Math.min(arena?.bounds?.z||7.5,e.z));}
 const alive=s.enemies.filter(e=>e.hp>0);for(let i=0;i<alive.length;i++){const a=alive[i];for(const b of alive.slice(i+1)){let dx=b.x-a.x,dz=b.z-a.z,d=Math.hypot(dx,dz);if(d<.72){if(d<.001){dx=.01;d=.01;}const v=(.72-d)*.5;a.x-=dx/d*v;a.z-=dz/d*v;b.x+=dx/d*v;b.z+=dz/d*v;}}const dx=p.x-a.x,dz=p.z-a.z,d=Math.hypot(dx,dz);if(d<.7&&d>.001){p.x+=dx/d*(.7-d);p.z+=dz/d*(.7-d);}}
 p.x=Math.max(-(arena?.bounds?.x||7.5),Math.min(arena?.bounds?.x||7.5,p.x));p.z=Math.max(-(arena?.bounds?.z||7.5),Math.min(arena?.bounds?.z||7.5,p.z));if(arena){arena.resolve(p);for(const e of alive)arena.resolve(e,.36);}if(s.hp<=0)s.ended=true;return events;}
