import {kneeGuardViewPose,updateKneeSide} from './knee-guard.js';import {setupTraining} from './training.js';import {mountTrainingPanel} from './training-panel.js';import {lockHands} from './arm-lock.js';import {WoundJets} from './wound.js';
import {showFists} from './punch.js';
import {CONTROLS,BINDING_MOVES,heldGuard,pressBinding,defenseHint,readyFists} from './bindings.js';
import {mountBindingEditor} from './binding-editor.js';
import {guardPose,guardHands} from './guard.js';
import {newPlayback,stepPlayback} from './combos.js';
import {inputLabel} from './input.js';
import {mountComboEditor} from './combo-editor.js';
import {PARTS,mobility,bleedRate} from './injury.js';
import {MAPS,loadMap} from './maps/registry.js';import {mountMap,mountMapPicker} from './maps/manager.js';import {loadQuality,applyQuality,mountQualityPicker} from './quality.js';
import {updateViewVisibility} from './viewmodel.js';
import {movePlayer} from './movement.js';
import {FightAudio} from './audio.js';
import * as T from './vendor/three.module.js';import {FighterRig,Ragdoll,pose,reactPose,enemyPose} from './rig.js?v=048';import {createState,beginAttack,tick,strikeHit,ATTACKS} from './combat.js';import {ScenePass} from './retro.js';import {Blood} from './fx.js';
const $=id=>document.getElementById(id),scene=new T.Scene();const renderer=new T.WebGLRenderer({antialias:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;$('view').append(renderer.domElement);const camera=new T.PerspectiveCamera(76,16/9,.05,70);scene.add(camera);
let storage;try{storage=localStorage;}catch{}let mapId=loadMap(storage),qualityId=loadQuality(storage),arena=mountMap(scene,mapId);
const handsScene=new T.Scene(),handsCamera=new T.PerspectiveCamera(76,innerWidth/innerHeight,.03,8);handsScene.add(handsCamera);handsScene.add(new T.HemisphereLight(0xffedcf,0x596453,2.7));const playerRig=new FighterRig();handsCamera.add(playerRig.root);playerRig.root.position.set(0,-1.67,-.32);
updateViewVisibility(playerRig,null);
playerRig.root.traverse(o=>{if(o.isMesh)o.castShadow=false;});
const composite=new ScenePass(renderer),blood=new Blood(scene),woundJets=new WoundJets();let bloodScreen=0;
const fightAudio=new FightAudio();let hitstop=0,recoil=0,roll=0,swayX=0,swayY=0,mouseFallback=false;

let s=createState(),p={...arena.entry.spawn},running=false,paused=true,started=false,rigs=new Map(),corpses=[],particles=[],held=new Set(),time=0,last=0,acc=0,hitFlash=0,damageFlash=0,shake=0,noticeTime=0,drag=false;
let bindings=mountBindingEditor(value=>{bindings=value;updateBindingLabels();});updateBindingLabels();
let playback=null;let savedCombos=mountComboEditor(value=>{savedCombos=value;updateComboHints();});updateComboHints();
function notify(text){$('notice').textContent=text;noticeTime=2.5;}
function reset(){playback=null;for(const r of rigs.values())scene.remove(r.root);for(const c of corpses)scene.remove(c.rig.root);for(const a of particles)scene.remove(a.mesh);rigs.clear();corpses=[];particles=[];s=createState();if(arena.entry.mode==='training')setupTraining(s,trainingPanel.config);p={...arena.entry.spawn};time=0;hitstop=0;recoil=0;roll=0;hitFlash=0;damageFlash=0;shake=0;acc=0;bloodScreen=0;blood.reset();woundJets.reset();started=true;}
function pause(){playback=null;s.guard=null;s.kneeActive=false;paused=true;running=false;held.clear();p.vx=0;p.vz=0;document.exitPointerLock?.();$('overlay').hidden=false;$('title').innerHTML=s.ended?'胜负已分。<br>再炼拳脚。':'收势。<br>择机再入。';$('copy').textContent=s.ended?`战至第 ${s.wave} 回合，击倒 ${s.kills} 人。`:'打、極、投、絞，各有其道。在自定义招式中设置四个按键的单招；攻击点按、防守按住，连招按 1–3 施放。';$('start').textContent=s.ended?'重入试炼':arena.entry.mode==='training'?'继续训练':'继续试炼';}
function fallbackLook(){mouseFallback=true;$('status').textContent='鼠标直接环视 · 当前浏览器不支持锁定';notify('鼠标已接管视角；完整无限转向请用桌面浏览器');}
function captureMouse(){mouseFallback=false;try{if(!renderer.domElement.requestPointerLock){fallbackLook();return;}const request=renderer.domElement.requestPointerLock();request?.catch(fallbackLook);}catch{fallbackLook();}}
$('start').disabled=false;$('start').textContent='入场 · 打击试炼';$('status').textContent='「打」· 拳峰直拳 / 掌击 / 正蹬';$('start').onclick=()=>{if(!started||s.ended)reset();fightAudio.unlock();paused=false;running=true;held.clear();$('overlay').hidden=true;acc=0;captureMouse();};$('pause').onclick=pause;
$('sensitivity').oninput=e=>{$('sensitivity-value').textContent=Number(e.target.value).toFixed(1);};
$('volume').oninput=e=>{fightAudio.volume=Number(e.target.value);if(fightAudio.master)fightAudio.master.gain.value=fightAudio.volume;};
document.addEventListener('pointerlockerror',()=>{if(running)fallbackLook();});
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement===renderer.domElement){mouseFallback=false;$('status').textContent='鼠标已锁定 · ESC 暂停';}else if(running&&!mouseFallback)pause();});window.addEventListener('blur',()=>{if(running)pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)pause()});window.addEventListener('keydown',e=>{if(!running&&['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const comboSlot=running&&!e.repeat?savedCombos.findIndex(c=>c.input===e.code):-1;if(comboSlot>=0){e.preventDefault();held.add(e.code);launchCombo(comboSlot);return;}if(['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyP','Escape','KeyQ','KeyE','KeyX'].includes(e.code)){e.preventDefault();held.add(e.code);if(running&&!e.repeat){if(['KeyQ','KeyE','KeyX'].includes(e.code))playback=null;if(e.code==='KeyQ'||e.code==='KeyE')useBinding(e.code);}if(e.code==='Escape'&&running)pause();if(e.code==='KeyP'&&!e.repeat){if(running)pause();else $('start').click();}}});window.addEventListener('keyup',e=>held.delete(e.code));renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('mousedown',e=>{if(!running)return;if(e.button===1){drag=true;e.preventDefault();return;}if(e.button===0||e.button===2||e.button===3||e.button===4){e.preventDefault();const key='Mouse'+e.button;held.add(key);const ci=savedCombos.findIndex(c=>c.input===key);if(ci>=0)launchCombo(ci);else useBinding(key);}});window.addEventListener('mouseup',e=>{held.delete('Mouse'+e.button);if(e.button===1)drag=false;});window.addEventListener('mousemove',e=>{if(!running||(!document.pointerLockElement&&!mouseFallback&&!drag))return;const sensitivity=Number($('sensitivity').value)*.002;const dx=e.movementX,dy=e.movementY;p.yaw-=dx*sensitivity;p.pitch=T.MathUtils.clamp(p.pitch-dy*sensitivity,-1.35,1.35);swayX=T.MathUtils.clamp(swayX-dx*.0006,-.035,.035);swayY=T.MathUtils.clamp(swayY+dy*.0006,-.025,.025);});
function effects(e){if(e.type==='guarded'){notify('对手提膝格挡');fightAudio.play('palm',0);hitFlash=.5;}if(e.type==='locked')notify('叠肘折腕成功');if(e.type==='kneeling')notify('弹腿命中 · 单膝跪地硬直 3 秒');if(e.type==='slowed')notify('躯干受创 · 减速 3 秒');if(e.type==='block'){notify((BINDING_MOVES[e.move]?.label||'攻击')+' · '+(e.guard==='headKnee'?'护头＋提膝格挡':e.guard==='knee'?'提膝格挡 · 格挡':e.zone==='head'?'头部防守 · 格挡':'三战躯干防守 · 格挡'));fightAudio.play('palm',0);recoil=.025;shake=.025;}if(e.type==='sever'){const r=rigs.get(e.enemy.id);r?.setInjuries(e.enemy);woundJets.add(r,e.part);blood.explode(new T.Vector3(...e.pos),new T.Vector3(e.enemy.vx,.8,e.enemy.vz).normalize());notify(PARTS[e.part].label+'损毁 · 持续失血');}if(e.type==='stunned')notify('头部重创 · 短暂击晕');if(e.type==='bleed'){const y=mobility(e.enemy).mode.includes('crawl')||mobility(e.enemy).mode==='drag'||mobility(e.enemy).mode==='wriggle'?.25:.7;blood.drip(new T.Vector3(e.enemy.x,y,e.enemy.z));}if(e.type==='wave'){fightAudio.play('wave');notify(`第 ${s.wave} 回合 · ${s.enemies.filter(e=>e.hp>0).length} 名对手`);s.enemies=s.enemies.filter(e=>e.hp>0);}if(e.type==='hurt'){damageFlash=1;shake=e.heavy?.28:.15;bloodScreen=Math.min(.95,bloodScreen+.4);fightAudio.play('hurt');notify((BINDING_MOVES[e.move]?.label||'攻击')+(e.zone==='head'?' · 命中头部':' · 命中躯干'));}if(e.type==='hit'){notify(PARTS[e.part].label+' −'+e.damage+(e.attack==='palm'?' · 击退':e.attack==='punch'?' · 踉跄':'')+(e.blocked?' · 手臂承伤':''));hitFlash=1;const heavy=e.attack==='kick';shake=heavy?.12:.08;hitstop=Math.max(hitstop,heavy?.07:.05);recoil=heavy?.06:.035;roll=(s.attack?.side?1:-1)*(heavy?.022:.013);fightAudio.play(e.attack,s.attack?.side||0);$('hitmark').classList.toggle('heavy',heavy);const hy=e.head?1.78:1.05+Math.random()*.35,bd=new T.Vector3(e.enemy.x-p.x,0,e.enemy.z-p.z).normalize(),bp=e.pos?[e.pos[0],Math.max(.2,e.pos[1]),e.pos[2]]:[e.enemy.x,hy,e.enemy.z];blood.burst(new T.Vector3(...bp),bd,!!e.head);bloodScreen=Math.min(.85,bloodScreen+(e.head?.6:.2));if(e.head){hitstop=Math.max(hitstop,.12);shake=.17;}}if(e.type==='down'){fightAudio.play('down');hitstop=Math.max(hitstop,.16);shake=.3;$('hitmark').classList.add('heavy');const r=rigs.get(e.enemy.id);if(r){r.flash(false);r.setInjuries(e.enemy);blood.explode(new T.Vector3(e.enemy.x,1.15,e.enemy.z),new T.Vector3(e.enemy.vx,.6,e.enemy.vz).normalize());bloodScreen=Math.min(.95,bloodScreen+.45);const c=new Ragdoll(r,r.lastPose||pose(time,0),{x:e.enemy.vx,z:e.enemy.vz},arena.bounds);corpses.push(c);rigs.delete(e.enemy.id);if(corpses.length>10)scene.remove(corpses.shift().rig.root);}notify(e.cause==='bleeding'?'失血致死':e.cause==='head'?'头部致命伤':'躯干致命伤');}}
function launchCombo(i){const combo=savedCombos[i];if(combo.steps.length){playback=newPlayback(combo);notify(combo.name);}else notify('该栏位为空 · 在暂停页编排招式');}
function updateComboHints(){const el=$('combo-hint');if(el)el.textContent=savedCombos.map(c=>inputLabel(c.input)).join(' / ');}
function pollGamepads(){for(const g of(navigator.getGamepads?navigator.getGamepads():[]))if(g)for(let i=0;i<g.buttons.length;i++){const id='Pad'+i,b=!!g.buttons[i]&&g.buttons[i].pressed;if(b&&!held.has(id)){held.add(id);const ci=savedCombos.findIndex(c=>c.input===id);if(ci>=0)launchCombo(ci);}else if(!b&&held.has(id))held.delete(id);}}
function simulate(dt){time+=dt;pollGamepads();s.guard=null;const manual=heldGuard(bindings,held);if(manual&&!s.attack)s.guard=manual;else if(playback){const result=stepPlayback(playback,dt,!!s.attack,(type,side)=>{s.sides[type]=side;const ok=beginAttack(s,type,{p,arena});if(ok&&type!=='armLock')fightAudio.play('swing-'+type,side);return ok;});s.guard=result.guard;if(result.done)playback=null;}updateKneeSide(s);$('action-state').textContent=s.guard?(s.guard==='headKnee'?'护头＋提膝格挡':s.guard==='knee'?'提膝格挡 · 防腿法中下段':s.guard==='head'?'小臂合拢护头':'三战躯干防守'):(playback?playback.combo.name+' · '+playback.index+'/'+playback.combo.steps.length:'');p.yaw+=(Number(held.has('ArrowLeft'))-Number(held.has('ArrowRight')))*dt*1.8;p.pitch=T.MathUtils.clamp(p.pitch+(Number(held.has('ArrowUp'))-Number(held.has('ArrowDown')))*dt,-1.35,1.35);let f=Number(held.has('KeyW'))-Number(held.has('KeyS')),r=Number(held.has('KeyD'))-Number(held.has('KeyA')),len=Math.hypot(f,r)||1;movePlayer(p,{forward:f,right:r,sprint:held.has('ShiftLeft')},dt);for(const e of tick(s,p,dt,arena))effects(e);
 for(const e of s.enemies){if(e.hp<=0)continue;let rig=rigs.get(e.id);if(!rig){rig=new FighterRig([0x934a35,0x71827c,0xb59b63,0x6d667c][e.id%4]);rigs.set(e.id,rig);scene.add(rig.root);}const previous=rig.previous||{x:e.x,z:e.z};const dx=e.x-previous.x,dz=e.z-previous.z;rig.previous={x:e.x,z:e.z};rig.root.position.set(e.x,0,e.z);const angle=Math.atan2(-(p.x-e.x),-(p.z-e.z));rig.root.rotation.set(0,angle,0,'YXZ');const speed=Math.hypot(dx,dz)/dt,moving=Math.min(1,speed/1.5);rig.gait=(rig.gait||0)+dt*(.5+moving*.5);const forward=-(dx*Math.sin(angle)+dz*Math.cos(angle))/(Math.hypot(dx,dz)||1),right=(dx*Math.cos(angle)-dz*Math.sin(angle))/(Math.hypot(dx,dz)||1);const attack=e.atk?{type:e.atk.type,side:e.atk.side,t:e.atk.t}:null;const current=enemyPose(e,rig.gait+e.phase,e.atk?0:moving,attack,{forward,right});e.pose=current;rig.set(current);rig.setInjuries(e);rig.setHands(attack&&!attack.side?.05:.8,attack&&attack.side?.05:.8);guardHands(rig,e.guard);showFists(rig,current,attack,e.guard,['punch','hook','uppercut'].includes((e.moves||[]).find(type=>['palm','punch','hook','uppercut'].includes(type))));rig.react(e.reaction);rig.flash(e.flash>0||!!e.atk&&e.atk.t<ATTACKS[e.atk.type].active&&Math.sin(time*25)>0);}

 for(const c of corpses)c.step(dt);woundJets.step(dt,(pos,dir,strength)=>blood.jet(pos,dir,strength));for(let i=particles.length-1;i>=0;i--){const a=particles[i];a.life-=dt;a.v.y-=7*dt;a.mesh.position.addScaledVector(a.v,dt);if(a.life<=0){scene.remove(a.mesh);a.mesh.geometry.dispose();a.mesh.material.dispose();particles.splice(i,1);}}
 hitFlash=Math.max(0,hitFlash-dt*7);damageFlash=Math.max(0,damageFlash-dt*2.5);shake*=Math.pow(.002,dt);noticeTime-=dt;if(noticeTime<=0)$('notice').textContent='';const handPose=pose(time,Math.min(1,Math.hypot(f,r))*.25,s.attack,{forward:f,right:r});for(const side of ['L','R']){handPose[side+'elbow'][0]*=1.2;handPose[side+'elbow'][1]-=.08;handPose[side+'wrist'][1]-=.08;}const ka=s.attack;if(ka&&ka.type==='kick'){const ks=ka.side?'R':'L',q=ks==='R'?1:-1,L=(a,b,e)=>a.map((x,i)=>x+(b[i]-x)*e),K=(kp,fp)=>{handPose[ks+'knee']=[q*kp[0],kp[1]+1.67,kp[2]+.32];handPose[ks+'ankle']=[q*fp[0],fp[1]+1.67,fp[2]+.32];};if(ka.t<.16){const e=1-(1-ka.t/.16)**3;K(L([.1,-1.15,-.5],[.24,-.55,-1.02],e),L([.1,-1.62,-.38],[.2,-.95,-.8],e));}else if(ka.t<.34){const v=(ka.t-.16)/.18,e=1-(1-v)*(1-v);K(L([.24,-.55,-1.02],[.18,-.48,-1.52],e),L([.2,-.95,-.8],[.13,-.4,-2.2],e));}else{const v=Math.min(1,(ka.t-.34)/.31),e=v*v*(3-2*v);K(L([.18,-.48,-1.52],[.1,-1.15,-.5],e),L([.13,-.4,-2.2],[.1,-1.62,-.38],e));}}guardPose(handPose,s.guard,null,s.kneeSide);kneeGuardViewPose(handPose,s.guard,s.kneeSide);playerRig.set(handPose);{const a=['kick','snapKick'].includes(s.attack?.type)?null:s.attack,ps=a&&a.type==='palm';playerRig.setHands(a&&!ps?.95:ps&&!a.side?.05:ps?.4:.8,a&&!ps?.95:ps&&a.side?.05:ps?.4:.8);}guardHands(playerRig,s.guard);showFists(playerRig,handPose,s.attack,s.guard,readyFists(bindings));lockHands(playerRig,s.attack);updateTarget();if(s.ended)pause();}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(running&&!paused){if(hitstop>0)hitstop=Math.max(0,hitstop-dt);acc+=dt*(hitstop>0?.05:1);while(acc>=1/60&&running){simulate(1/60);acc-=1/60;}}if(running){recoil*=Math.exp(-dt*17);roll*=Math.exp(-dt*18);swayX*=Math.exp(-dt*12);swayY*=Math.exp(-dt*12);}playerRig.root.position.x=swayX;playerRig.root.position.y=-1.67+swayY;playerRig.root.position.z=-.32+recoil;camera.fov=76+recoil*26;camera.updateProjectionMatrix();camera.position.set(p.x+(Math.random()-.5)*shake,1.7+Math.sin(time*12)*.012+(Math.random()-.5)*shake,p.z+(Math.random()-.5)*shake);camera.rotation.set(p.pitch+recoil*.4+(Math.random()-.5)*shake*.4,p.yaw+(Math.random()-.5)*shake*.4,roll+(Math.random()-.5)*shake*.5,'YXZ');updateViewVisibility(playerRig,s.attack,s.guard,s.kneeSide);playerRig.root.visible=started;if(!started){camera.position.set(...arena.entry.preview.eye);camera.lookAt(...arena.entry.preview.target);}arena.update?.(time);composite.begin();renderer.render(scene,camera);renderer.autoClear=false;renderer.clearDepth();handsCamera.fov=camera.fov;handsCamera.updateProjectionMatrix();renderer.render(handsScene,handsCamera);renderer.autoClear=true;if(running)blood.step(dt);bloodScreen=Math.max(0,bloodScreen-dt*.16);composite.mat.uniforms.blood.value=bloodScreen;composite.mat.uniforms.tBlood.value=blood.splats[blood.splatIdx];composite.present(now/1000);$('hp').textContent=s.hp;$('bar').style.width=s.hp+'%';$('wave').textContent=arena.entry.mode==='training'?'自由训练':'第 '+String(s.wave||1).padStart(2,'0')+' 回合';$('remaining').textContent=s.enemies.some(e=>e.hp>0)?s.enemies.filter(e=>e.hp>0).length+' 名对手':(s.training?(s.training.count===0?'空场 · 动作演示':s.training.respawn?'对手准备中':'练习完成 · 暂停可重置'):`下一回合 ${Math.max(0,Math.ceil(s.waveDelay))}s`);$('kills').textContent=String(s.kills).padStart(2,'0');$('hitmark').style.opacity=hitFlash;$('damage').style.opacity=damageFlash;requestAnimationFrame(frame);}function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();handsCamera.aspect=innerWidth/innerHeight;handsCamera.updateProjectionMatrix();composite.resize();}window.addEventListener('resize',resize);resize();requestAnimationFrame(frame);


function updateTarget(){const hits=s.enemies.filter(e=>e.hp>0).map(e=>({e,h:strikeHit(p,e,{range:5,r:.025})})).filter(x=>x.h&&arena.clear(p,x.e)).sort((a,b)=>a.h.distance-b.h.distance);const box=$('target-health');if(!hits.length){box.hidden=true;return;}const{e,h}=hits[0];box.hidden=false;$('target-title').textContent=PARTS[h.part].label+' · '+(e.wind>0?(e.attackZone==='head'?'高位来袭 · '+defenseHint(bindings,'head'):'中段来袭 · '+defenseHint(bindings,'torso')):mobility(e).label+(e.slow>0?' · 减速':''));for(const[key,part]of Object.entries(e.body)){const row=$('part-'+key);row.querySelector('i').style.width=(part.hp/part.max*100)+'%';row.querySelector('b').textContent=part.gone?'缺失':Math.ceil(part.hp);row.classList.toggle('aimed',key===h.part);}$('blood-value').textContent='血量 '+Math.ceil(e.blood)+' / 100'+(bleedRate(e)>0?' · 失血 '+bleedRate(e).toFixed(1)+'/秒':'');}

function useBinding(key) {
  playback = null;
  if (pressBinding(s, bindings, key, held,{p,arena})&&s.attack.type!=='armLock') fightAudio.play('swing-' + s.attack.type, s.attack.side);
}
function updateBindingLabels() {
  for (const [key,label] of Object.entries(CONTROLS)) {
    document.getElementById('hint-' + key).textContent = label + ' · ' + BINDING_MOVES[bindings[key]].label;
  }
}

function refreshQuality(){applyQuality(qualityId,renderer,composite,scene,innerWidth,innerHeight,devicePixelRatio);}
function refreshMapLabels(){camera.far=arena.entry.far??70;camera.updateProjectionMatrix();renderer.toneMappingExposure=arena.entry.exposure??1.35;
  document.body.classList.toggle('bright-map',!!arena.entry.bright);document.body.classList.toggle('training-mode',arena.entry.mode==='training');trainingPanel.setVisible(arena.entry.mode==='training');if(!started)$('start').textContent=arena.entry.mode==='training'?'入场 · 自由训练':'入场 · 打击试炼';const name=MAPS[mapId].name;document.title='打極投絞 · '+name;
  document.querySelector('.stats .center small').textContent=name+(arena.entry.mode==='training'?' · 自由训练':' · 打击试炼');
  document.querySelector('.card > p').textContent=name+(arena.entry.mode==='training'?' / 训练与演示':' / 第一章 · 打');
  document.querySelector('.scene-label').innerHTML=name+'<br><strong>以打入局。<br>以技决胜。</strong>';
}
mountQualityPicker(qualityId,id=>{qualityId=id;refreshQuality();});
mountMapPicker(mapId,id=>{
  reset();arena.dispose();mapId=id;arena=mountMap(scene,id);p={...arena.entry.spawn};started=false;running=false;paused=true;held.clear();
  $('target-health').hidden=true;$('notice').textContent='';$('action-state').textContent='';$('start').textContent='入场 · 打击试炼';
  refreshQuality();refreshMapLabels();
});
const trainingPanel=mountTrainingPanel(storage,()=>{if(arena.entry.mode==='training'){reset();updateTarget();}},()=>{reset();updateTarget();});
refreshQuality();refreshMapLabels();
