import test from 'node:test';import assert from 'node:assert/strict';import {guardPose,guardBlocks} from './guard.js';import {pose,enemyPose} from './rig.js';import {MOVES,validateCombo,newPlayback,stepPlayback,loadCombos} from './combos.js';import {createState,tick,beginAttack,strikeHit,ATTACKS} from './combat.js';import {initBody} from './injury.js';
test('head guard forearms stay parallel on their own side, with wrists above elbows',()=>{const q=guardPose(pose(),'head');for(const s of['L','R']){assert.equal(q[s+'elbow'][0],q[s+'wrist'][0]);assert.ok(q[s+'wrist'][1]-q[s+'elbow'][1]>.35);}assert.ok(q.Lwrist[0]<0&&q.Rwrist[0]>0);});
test('Sanchin keeps elbows tucked and hands in front of chest, distinct from head guard',()=>{const p=guardPose(pose(),'torso');assert.ok(p.Lelbow[0]>p.Lwrist[0]);assert.ok(p.Relbow[0]<p.Rwrist[0]);assert.ok(p.Lwrist[1]<1.5&&p.Lelbow[1]<1.2);});
test('matching frontal guard blocks, wrong zone and rear remain exposed',()=>{const p={x:0,z:0,yaw:0};assert.ok(guardBlocks('head','head',p,{x:0,z:-1}));assert.ok(!guardBlocks('head','torso',p,{x:0,z:-1}));assert.ok(!guardBlocks('torso','torso',p,{x:0,z:1}));});
test('actual AI strike emits block with matching defense and hurt otherwise',()=>{for(const guard of['head','torso',null]){const s=createState();s.guard=guard;s.enemies=[initBody({id:0,x:0,z:-1,hp:100,vx:0,vz:0,stun:0,cool:9,phase:0,flash:0,atk:{type:'punch',side:0,t:.14,hit:false,zone:'head'}})];const ev=tick(s,{x:0,z:0,yaw:0},.02);assert.equal(s.hp,guard==='head'?100:86);assert.ok(ev.some(e=>e.type===(guard==='head'?'block':'hurt')&&e.move==='punch'));assert.equal(beginAttack({...s,guard:'head'},'palm'),false);}});
test('head guard collider intercepts a frontal head-directed strike',()=>{const e=initBody({x:0,z:-1.5,hp:100,guard:'head',stun:0});e.pose=enemyPose(e);assert.match(strikeHit({x:0,z:0,yaw:0,pitch:.05},e,ATTACKS.palm).part,/arm$/);});
test('fifteen moves validate, invalid names and durations rejected',()=>{assert.equal(Object.keys(MOVES).length,15);assert.equal(validateCombo({name:'试炼',steps:Object.keys(MOVES).slice(0,12).map(move=>({move,hold:.5}))}).steps.length,12);assert.throws(()=>validateCombo({name:'bad',steps:[{move:'fake'}]}));assert.throws(()=>validateCombo({name:'bad',steps:[{move:'guardHead',hold:99}]}));});
test('combo waits for recovery, respects explicit sides and holds defense for its duration',()=>{const p=newPlayback({name:'连击',steps:[{move:'palmL'},{move:'palmR'},{move:'guardTorso',hold:.6},{move:'kickL'}]});const calls=[],start=(...args)=>{calls.push(args);return true;};stepPlayback(p,.1,false,start);stepPlayback(p,.1,true,start);assert.equal(calls.length,1);stepPlayback(p,.1,false,start);assert.deepEqual(calls,[['palm',0],['palm',1]]);assert.equal(stepPlayback(p,.1,false,start).guard,'torso');for(let i=0;i<4;i++)assert.equal(stepPlayback(p,.1,false,start).guard,'torso');stepPlayback(p,.3,false,start);assert.deepEqual(calls.at(-1),['kick',0]);assert.equal(stepPlayback(p,.1,false,start).done,true);});
test('saved slots round-trip with trigger inputs and corrupt storage safely falls back',()=>{const slots=[1,2,3].map(i=>({name:'招式 '+i,steps:[{move:'kickR',hold:.6}],input:'Digit'+i}));assert.deepEqual(loadCombos({getItem:()=>JSON.stringify(slots)}),slots);assert.deepEqual(loadCombos({getItem:()=>JSON.stringify([1,2,3].map(i=>({name:'旧 '+i,steps:[]})))}).map(c=>c.input),['Digit1','Digit2','Digit3']);assert.equal(loadCombos({getItem:()=>'{broken'}).length,3);assert.equal(loadCombos(undefined)[0].steps.length,0);});
