// Shared injury rules. Limb health never substitutes for vital-organ health.
export const PARTS={head:{label:'头部',hp:100,mult:2.4},torso:{label:'躯干',hp:120,mult:1},Larm:{label:'左臂',hp:48,mult:.55,bleed:4},Rarm:{label:'右臂',hp:48,mult:.55,bleed:4},Lleg:{label:'左腿',hp:55,mult:.55,bleed:6},Rleg:{label:'右腿',hp:55,mult:.55,bleed:6},Lfoot:{label:'左脚',hp:42,mult:1.65,bleed:2.5},Rfoot:{label:'右脚',hp:42,mult:1.65,bleed:2.5}};
export function initBody(e){if(!e.body)e.body=Object.fromEntries(Object.entries(PARTS).map(([k,v])=>[k,{hp:v.hp,max:v.hp,gone:false}]));e.blood??=100;e.ko??=0;return e;}
export function isGone(e,part){return !!e.body?.[part]?.gone;}
export function bleedRate(e){return Object.entries(PARTS).reduce((n,[k,v])=>n+(isGone(e,k)&&!(k.endsWith('foot')&&isGone(e,k[0]+'leg'))?(v.bleed||0):0),0);}
export function mobility(e){const legs=Number(isGone(e,'Lleg'))+Number(isGone(e,'Rleg')),arms=Number(!isGone(e,'Larm'))+Number(!isGone(e,'Rarm')),feet=Number(isGone(e,'Lfoot'))+Number(isGone(e,'Rfoot'));if(e.ko>0)return {mode:'stunned',speed:0,label:'击晕'};if(legs)return {mode:arms===2?'crawl':arms===1?'drag':'wriggle',speed:arms===2?.30:arms===1?.18:.075,label:arms===2?'双臂爬行':arms===1?'单臂拖行':'躯干挪行'};if(e.kneel>0)return {mode:'kneel',speed:0,label:'单膝跪地 · 硬直'};if(feet===1)return {mode:'limp',speed:.55,label:'跛行'};if(feet===2)return {mode:'slowWalk',speed:.22,label:'双脚缺失'};return {mode:'walk',speed:1,label:'站立'};}
export function damagePart(e,part,base,rng=Math.random){initBody(e);const b=e.body[part];if(!b||b.gone||e.hp<=0)return null;const damage=Math.round(base*PARTS[part].mult);b.hp=Math.max(0,b.hp-damage);let severed=false,stunned=false,cause=null;if(part==='head'||part==='torso'){if(b.hp===0){e.hp=0;cause=part;}else if(part==='head'&&rng()<.08){e.ko=2.8;e.wind=0;stunned=true;}}else if(b.hp===0){b.gone=true;severed=true;if(part.endsWith('leg')){e.body[part[0]+'foot'].gone=true;e.body[part[0]+'foot'].hp=0;}}
return {part,damage,severed,stunned,cause};}
export function tickInjury(e,dt){initBody(e);if(e.hp<=0)return null;e.ko=Math.max(0,e.ko-dt);e.kneel=Math.max(0,(e.kneel||0)-dt);const rate=bleedRate(e);e.blood=Math.max(0,e.blood-rate*dt);if(e.blood===0){e.hp=0;return 'bleeding';}return null;}
