import {buildFist,punchPose} from './punch.js';
import {guardPose} from './guard.js';
import * as T from './vendor/three.module.js';
export const links=[['hip','chest',.55,.34,'cloth'],['chest','neck',.50,.30,'cloth'],['neck','head',.13,.13,'skin'],...['L','R'].flatMap(s=>[[s+'shoulder',s+'elbow',.145,.15,'cloth'],[s+'elbow',s+'wrist',.105,.11,'skin'],[s+'hip',s+'knee',.165,.17,'pants'],[s+'knee',s+'ankle',.12,.13,'pants']])];
// Analytic two-bone IK with a fixed forward pole (-Z), including backward steps.
export function solveLeg(hip,foot,upper=.43,lower=.43){const h=new T.Vector3(...hip),target=new T.Vector3(...foot),axis=target.clone().sub(h);const d=T.MathUtils.clamp(axis.length(),.05,upper+lower-.008);axis.normalize();target.copy(h).addScaledVector(axis,d);const along=(upper*upper-lower*lower+d*d)/(2*d),height=Math.sqrt(Math.max(0,upper*upper-along*along));let pole=new T.Vector3(0,0,-1).addScaledVector(axis,axis.z);if(pole.lengthSq()<1e-6)pole.set(0,-1,0).addScaledVector(axis,axis.y);pole.normalize();return {knee:h.clone().addScaledVector(axis,along).addScaledVector(pole,height).toArray(),foot:target.toArray()};}
export function pose(t=0,move=0,attack=null,motion={forward:1,right:0}){const amount=Math.abs(move),bob=(1-Math.cos(t*16))*.012*amount,p={hip:[0,.91-bob,0],chest:[0,1.29-bob,-.025],neck:[0,1.49-bob,-.025],head:[0,1.7-bob,-.02]};const direction=move<0?-1:motion.forward,n=Math.max(1,Math.hypot(direction,motion.right));for(const [s,k]of[['L',-1],['R',1]]){const phase=t*8+(k===1?Math.PI:0),stride=Math.sin(phase)*.27*amount,lift=Math.max(0,Math.cos(phase))*.095*amount;p[s+'shoulder']=[k*.265,1.43-bob,0];p[s+'elbow']=[k*.33,1.15-bob,-.20-stride*.25];p[s+'wrist']=[k*.23,1.38-bob,-.39-stride*.32];p[s+'hip']=[k*.16,.91-bob,0];const target=[k*.18+stride*motion.right/n,.10+lift,-stride*direction/n];const leg=solveLeg(p[s+'hip'],target);p[s+'knee']=leg.knee;p[s+'ankle']=leg.foot;}
if(attack?.type==='punch')return punchPose(p,attack);if(attack){const s=attack.side?'R':'L',k=attack.side?1:-1;if(attack.type==='palm'){const q=Math.sin(Math.min(1,attack.t/.34)*Math.PI);p[s+'elbow']=[k*.23,1.44,-.24-q*.3];p[s+'wrist']=[k*.18,1.46,-.43-q*.63];p.chest[2]-=q*.08;p[s+'shoulder'][2]-=q*.12;}else{const A=attack.t,M=(a,b,e)=>a+(b-a)*e;let ft,dr;if(A<.16){const e=1-(1-A/.16)**3;ft=[M(k*.18,k*.16,e),M(.10,.50,e),M(0,.14,e)];dr=e*.35;}else if(A<.34){const v=(A-.16)/.18,e=1-(1-v)*(1-v);ft=[M(k*.16,k*.2,e),M(.50,.99,e),M(.14,-1.06,e)];dr=.35+.65*e;}else if(A<.42){ft=[k*.2,.99,-1.06];dr=1;}else{const v=Math.min(1,(A-.42)/.23),e=v*v*(3-2*v);ft=[M(k*.2,k*.18,e),M(.99,.10,e),M(-1.06,0,e)];dr=1-.7*e;}const leg=solveLeg(p[s+'hip'],ft);p[s+'knee']=leg.knee;p[s+'ankle']=leg.foot;p.chest[2]+=dr*.16;p.hip[2]-=dr*.07;p.chest[0]+=k*dr*.04;for(const w of['L','R']){p[w+'elbow'][2]+=dr*.13;p[w+'wrist'][2]+=dr*.22;p[w+'wrist'][1]-=dr*.12;}}}return p;}
export function reactPose(p,reaction){if(!reaction||reaction.age>=reaction.duration)return p;const age=reaction.age||0,duration=reaction.duration||.6,progress=Math.min(1,age/duration);const impact=(1-Math.exp(-age*65))*Math.pow(1-progress,1.45),side=reaction.side||1,head=reaction.head,kick=reaction.type==='kick';const hinge=head?.22:kick?-.60:-.37,twist=side*(head?.28:.16);for(const name of ['chest','neck','head','Lshoulder','Rshoulder','Lelbow','Relbow','Lwrist','Rwrist']){const v=new T.Vector3(...p[name]).sub(new T.Vector3(...p.hip));v.applyEuler(new T.Euler(hinge*impact,twist*impact,-side*.12*impact));v.add(new T.Vector3(...p.hip));p[name]=v.toArray();}p.head[0]+=side*(head?.12:.035)*impact;p.head[2]+=(head?.10:-.02)*impact;for(const s of ['L','R']){const k=s==='L'?-1:1;p[s+'elbow'][0]+=k*.14*impact;p[s+'wrist'][1]-=.22*impact;p[s+'wrist'][2]+=.1*impact;const foot=p[s+'ankle'].slice();foot[2]+=Math.sin(progress*Math.PI)*.20*(kick?1.7:1)*(s===(side>0?'R':'L')?1:.3);foot[1]+=Math.sin(progress*Math.PI)*.08;const leg=solveLeg(p[s+'hip'],foot);p[s+'knee']=leg.knee;p[s+'ankle']=leg.foot;}return p;}
export class FighterRig{
 constructor(color=0x777f71){this.root=new T.Group();this.parts=[];this.materials={cloth:new T.MeshStandardMaterial({color,roughness:.88}),pants:new T.MeshStandardMaterial({color:0x253331,roughness:.86}),skin:new T.MeshStandardMaterial({color:0xc99b78,roughness:.72}),joint:new T.MeshStandardMaterial({color:0x242927,roughness:.85}),wrap:new T.MeshStandardMaterial({color:0xc8bca2,roughness:1})};const bone=new T.BoxGeometry(1,1,1),sphere=bone;for(const link of links){const mesh=new T.Mesh(bone,this.materials[link[4]]);mesh.castShadow=true;mesh.receiveShadow=true;this.root.add(mesh);this.parts.push({mesh,link});}this.joints={};for(const name of Object.keys(pose())){if(['hip','chest','neck','head'].includes(name))continue;const key=name.includes('shoulder')?'cloth':name.includes('hip')||name.includes('knee')||name.includes('ankle')?'pants':'skin';const mesh=new T.Mesh(sphere,this.materials[key]);mesh.scale.setScalar(name.includes('shoulder')?.15:name.includes('hip')?.165:name.includes('knee')?.13:.10);this.root.add(mesh);this.joints[name]=mesh;}this.ends={};for(const name of ['Lwrist','Rwrist','Lankle','Rankle','head']){const mesh=new T.Mesh(sphere,this.materials[name.includes('ankle')?'joint':name.includes('wrist')?'skin':'skin']);mesh.castShadow=true;this.root.add(mesh);this.ends[name]=mesh;}
 for(const x of[-.24,.24]){const eye=new T.Mesh(bone,this.materials.joint);eye.position.set(x,.035,-.512);eye.scale.set(.14,.10,.035);this.ends.head.add(eye);const brow=new T.Mesh(bone,this.materials.joint);brow.position.set(x,.15,-.515);brow.scale.set(.20,.045,.035);this.ends.head.add(brow);}const nose=new T.Mesh(bone,this.materials.skin);nose.scale.set(.14,.18,.13);nose.position.set(0,-.085,-.55);this.ends.head.add(nose);const mouth=new T.Mesh(bone,this.materials.joint);mouth.scale.set(.28,.045,.035);mouth.position.set(0,-.28,-.515);this.ends.head.add(mouth);const hair=new T.Mesh(bone,this.materials.joint);hair.position.set(0,.45,0);hair.scale.set(1.04,.20,1.04);this.ends.head.add(hair);this.hands={};this.curl={L:.8,R:.8};
 for(const [s,k]of[['L',-1],['R',1]]){const g=new T.Group();const palm=new T.Mesh(bone,this.materials.skin);palm.castShadow=true;palm.scale.set(.15,.06,.13);palm.position.set(0,0,-.055);g.add(palm);const fingers=[];const f=new T.Group();f.position.set(0,-.004,-.12);const fm=new T.Mesh(bone,this.materials.skin);fm.castShadow=true;fm.scale.set(.12,.034,.058);fm.position.set(0,0,-.029);f.add(fm);const f2=new T.Group();f2.position.set(0,0,-.058);const gm=new T.Mesh(bone,this.materials.skin);gm.castShadow=true;gm.scale.set(.12,.028,.05);gm.position.set(0,0,-.025);f2.add(gm);f.add(f2);g.add(f);fingers.push([f,f2]);const th=new T.Group();th.position.set(-k*.075,-.008,-.06);const tm=new T.Mesh(bone,this.materials.skin);tm.castShadow=true;tm.scale.set(.03,.032,.075);tm.position.set(-k*.012,0,-.03);tm.rotation.z=(s==='L'?-1:1)*.18;th.add(tm);g.add(th);this.root.add(g);this.hands[s]={group:g,palm,fingers,thumb:th};}for(const side of ['L','R']){const h=this.hands[side];h.fist=buildFist(this.materials.skin,side);h.group.add(h.fist);}this.setHands(.8,.8);this.set(pose());}
 setHands(cL,cR){for(const [s,c]of[['L',cL],['R',cR]]){const h=this.hands[s];if(!h)continue;this.curl[s]=c;for(const [f,f2]of h.fingers){f.rotation.x=.12;f2.rotation.x=.08;}h.thumb.rotation.x=.45-c*1.5;h.thumb.rotation.y=(s==='L'?-1:1)*((1-c)*.85+.15);}}
 set(p){this.lastPose=Object.fromEntries(Object.entries(p).map(([k,v])=>[k,[...v]]));const up=new T.Vector3(0,1,0);for(const {mesh,link:[a,b,w,d]}of this.parts){const av=new T.Vector3(...p[a]),bv=new T.Vector3(...p[b]),v=bv.clone().sub(av);mesh.position.copy(av.add(bv).multiplyScalar(.5));mesh.scale.set(w,v.length()+.045,d);mesh.quaternion.setFromUnitVectors(up,v.normalize());}for(const[n,mesh]of Object.entries(this.joints))mesh.position.set(...p[n]);for(const[n,mesh]of Object.entries(this.ends)){mesh.position.set(...p[n]);if(n==='head')mesh.scale.set(.40,.44,.39);else if(n.includes('ankle')){mesh.scale.set(.21,.15,.37);mesh.position.z-=.07;}else mesh.scale.set(.09,.09,.10);}for(const s of['L','R']){const h=this.hands[s];if(!h)continue;const w=new T.Vector3(...p[s+'wrist']),e=new T.Vector3(...p[s+'elbow']);h.group.position.copy(w);const d=w.clone().sub(e);d.y*=.3;h.group.quaternion.setFromUnitVectors(new T.Vector3(0,0,-1),d.normalize());const o=Math.max(0,.6-this.curl[s])*2.2;h.group.rotateZ((s==='L'?-1:1)*.22);h.group.rotateX(.16+o);}}
 react(reaction){const x=reaction?Math.min(1,(reaction.age||0)/reaction.duration):1,force=(1-Math.exp(-(reaction?.age||0)*65))*Math.pow(1-x,1.45);this.ends.head.rotation.set((reaction?.head?.4:-.1)*force,(reaction?.side||1)*.5*force,(reaction?.side||1)*.18*force);}
 flash(v){for(const material of Object.values(this.materials)){material.emissive.setHex(v?0xff9b42:0);material.emissiveIntensity=v?.25:0;}}
}
// Position-based articulated ragdoll: joint constraints, gravity and floor friction.
export class Ragdoll{
 constructor(rig,p,velocity,bounds={x:7.7,z:7.7}){this.bounds=bounds;this.rig=rig;this.points={};this.old={};rig.root.updateMatrixWorld(true);for(const [k,v]of Object.entries(p)){const w=new T.Vector3(...v).applyMatrix4(rig.root.matrixWorld);this.points[k]=w;this.old[k]=w.clone().sub(new T.Vector3(velocity.x/60,(k==='head'?.9:1.7)/60,velocity.z/60));}this.constraints=links.map(([a,b])=>[a,b,this.points[a].distanceTo(this.points[b])]);for(const s of ['L','R'])for(const [a,b]of [[s+'shoulder','chest'],[s+'hip','hip'],[s+'shoulder','neck']])this.constraints.push([a,b,this.points[a].distanceTo(this.points[b])]);this.constraints.push(['Lhip','Rhip',.32],['Lshoulder','Rshoulder',.56],['hip','neck',.6]);rig.root.position.set(0,0,0);rig.root.rotation.set(0,0,0);this.age=0;}
 step(dt){this.age+=dt;if(this.age>6)return;for(const [k,p]of Object.entries(this.points)){const prev=this.old[k],v=p.clone().sub(prev).multiplyScalar(.985);prev.copy(p);p.add(v);p.y-=9.8*dt*dt;}for(let i=0;i<7;i++){for(const [a,b,len]of this.constraints){const d=this.points[b].clone().sub(this.points[a]),l=d.length()||.001;d.multiplyScalar((l-len)/l*.5);this.points[a].add(d);this.points[b].sub(d);}for(const [k,p]of Object.entries(this.points)){if(p.y<.12){p.y=.12;this.old[k].x+=(p.x-this.old[k].x)*.2;this.old[k].z+=(p.z-this.old[k].z)*.2;}p.x=T.MathUtils.clamp(p.x,-this.bounds.x,this.bounds.x);p.z=T.MathUtils.clamp(p.z,-this.bounds.z,this.bounds.z);}}this.rig.set(Object.fromEntries(Object.entries(this.points).map(([k,p])=>[k,p.toArray()])));}
}

// Injury poses share their joint positions with combat colliders.
export function injuryPose(p,e,t=0,move=0){const gone=k=>!!e.body?.[k]?.gone,missingLeg=gone('Lleg')||gone('Rleg');if(missingLeg||e.ko>0){const cycle=t*5,arms=Number(!gone('Larm'))+Number(!gone('Rarm')),sway=Math.sin(cycle)*.035*move;const ko=e.ko>0;p.hip=[sway,.25,.15];p.chest=[sway,.31,-.23];p.neck=[sway,.34,-.43];p.head=[sway,.39,-.62];for(const[s,k]of[['L',-1],['R',1]]){const ph=cycle+(s==='R'?Math.PI:0),pull=Math.sin(ph)*move;p[s+'hip']=[k*.16,.25,.15];p[s+'knee']=[k*.20,.15,.49];p[s+'ankle']=[k*.22,.11,.85];p[s+'shoulder']=[k*.27,.32,-.37];p[s+'elbow']=[k*(arms===1?.30:.36),.16,-.43-pull*.13];p[s+'wrist']=[k*.27,.08+Math.max(0,Math.cos(ph))*.075*move,-.65-pull*.25];if(e.wind>0&&!ko&&(e.attackSide===1?'R':'L')===s&&!gone(s+'arm')){p[s+'wrist'][2]-=Math.sin(Math.max(0,.65-e.wind)/.65*Math.PI)*.23;p[s+'wrist'][1]+=.14;}if(ko){p[s+'elbow']=[k*.39,.12,-.23];p[s+'wrist']=[k*.53,.09,-.42];}if(arms===1&&!gone(s+'arm')){p.chest[0]+=k*.045*Math.sin(cycle)*move;p.head[0]=p.chest[0];}if(arms===0&&!ko){p.hip[0]=Math.sin(cycle)*.10*move;p.chest[0]=-Math.sin(cycle)*.08*move;p.head[1]+=(1+Math.sin(cycle))* .035*move;}}return p;}
if(gone('Lfoot')!==gone('Rfoot')){const sign=gone('Lfoot')?1:-1,lean=sign*(.04+Math.sin(t*8)*.035*move);for(const n of['hip','chest','neck','head']){p[n][0]+=lean;p[n][1]-=(1+Math.sin(t*8))* .035*move;}for(const side of['L','R']){const leg=solveLeg(p[side+'hip'],p[side+'ankle']);p[side+'knee']=leg.knee;p[side+'ankle']=leg.foot;}}
if(e.guard&&e.stun<=0&&e.ko<=0)guardPose(p,e.guard===true?'head':e.guard,e.body);return p;}
export function enemyPose(e,t=0,move=0,attack=null,motion={forward:1,right:0}){const q=pose(t,move,attack,motion);if(attack&&e.attackZone==='head'){const side=attack.side?'R':'L';q[side+'wrist'][1]+=.25;q[side+'elbow'][1]+=.12;}return injuryPose(reactPose(q,e.reaction),e,t,move);}
FighterRig.prototype.setInjuries=function(e){const gone=k=>!!e.body?.[k]?.gone;for(const{mesh,link:[a]}of this.parts){const side=a[0];mesh.visible=!(a.includes('shoulder')||a.includes('elbow')?gone(side+'arm'):a.length>1&&(a.includes('hip')||a.includes('knee'))?gone(side+'leg'):false);}for(const[n,m]of Object.entries(this.joints)){const s=n[0];m.visible=!(n.includes('shoulder')||n.includes('elbow')||n.includes('wrist')?gone(s+'arm'):gone(s+'leg'));}for(const[n,m]of Object.entries(this.ends)){m.visible=n==='head'?true:n.includes('wrist')?!gone(n[0]+'arm'):!gone(n[0]+'leg')&&!gone(n[0]+'foot');}for(const[s,h]of Object.entries(this.hands))h.group.visible=!gone(s+'arm');};
